







// Generated by T4Template
using UnityEngine;
using System;
using Zara.Common.ExScene;

namespace Zara.Expansion.ExScene
{
    public partial class SceneLoader : ISceneLoader
    {
        public SceneLoader(SceneDirector sceneDirector)
        {
            LoadingActionCache<Zara.Main.Ui.Error.ErrorSceneStarter>.Action = onLoaded => sceneDirector.LoadFromBuiltinAsset("Error", onLoaded);
            LoadingActionCache<Zara.Main.Ui.Loading.LoadingSceneStarter>.Action = onLoaded => sceneDirector.LoadFromBuiltinAsset("Loading", onLoaded); 
            LoadingActionCache<Zara.Main.Ui.Title.TitleSceneStarter>.Action = onLoaded => sceneDirector.LoadFromAssetBundle("Title", onLoaded); 
            LoadingActionCache<Zara.Main.Ui.Download.DownloadSceneStarter>.Action = onLoaded => sceneDirector.LoadFromAssetBundle("Download", onLoaded); 
            LoadingActionCache<Zara.Main.Ui.First.FirstSceneStarter>.Action = onLoaded => sceneDirector.LoadFromAssetBundle("First", onLoaded); 
            LoadingActionCache<Zara.Main.Ui.Plane.PlaneSceneStarter>.Action = onLoaded => sceneDirector.LoadFromAssetBundle("Plane", onLoaded); 
            LoadingActionCache<Zara.Main.Ui.Header.HeaderSceneStarter>.Action = onLoaded => sceneDirector.LoadFromAssetBundle("Header", onLoaded); 
            LoadingActionCache<Zara.Main.Ui.Popup2d.Popup2dSceneStarter>.Action = onLoaded => sceneDirector.LoadFromAssetBundle("Popup2d", onLoaded); 
            LoadingActionCache<Zara.Main.Ui.Popup3d.Popup3dSceneStarter>.Action = onLoaded => sceneDirector.LoadFromAssetBundle("Popup3d", onLoaded);
        }
    }
}
